sudo: required
dist: bionic
os: linux

language: cpp

env:
  global:
    - BOOST_VERSION=1_72_0
    - BOOST_DOT_VER=1.72.0

before_install:
  - wget -O boost_${BOOST_VERSION}.tar.gz https://dl.bintray.com/boostorg/release/${BOOST_DOT_VER}/source/boost_${BOOST_VERSION}.tar.gz && tar -xzf boost_${BOOST_VERSION}.tar.gz
  - cd boost_${BOOST_VERSION}
  - ./bootstrap.sh --with-libraries=test > build.log 2>&1 || (cat build.log && exit 1)
  - sudo ./b2 install > build.log 2>&1 || (cat build.log && exit 1)
  - sudo ldconfig
  - sudo apt-get -y install libmysqlclient-dev libsqlite3-dev
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS test;'

services:
  - mysql

matrix:
  include:
    - env: CXX=g++-9 CC=gcc-9
      addons:
        apt:
          packages:
            - g++-9
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
    - env: CXX=g++-8 CC=gcc-8
      addons:
        apt:
          packages:
            - g++-8
    - env: CXX=g++-7 CC=gcc-7
      addons:
        apt:
          packages:
            - g++-7
    - env: CXX=clang++-9 CC=clang-9
      addons:
        apt:
          packages:
            - clang-10
            - libc++-10-dev
            - libc++abi-10-dev
          sources:
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'


script:
  - cd $TRAVIS_BUILD_DIR
  - if [[ "$CXX" == clang* ]]; then export CXXFLAGS="-stdlib=libc++"; fi
  - mkdir build && cd build
  - cmake -DDBM_BUILD_TESTS=ON ..
  - make
  - test/dbm_test --logger=HRF,all --color_output=true --report_format=HRF --show_progress=no -- --mysql-username root
